
# Use root/example as user/password credentials

services:
  mongo:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: alrussy
      MONGO_INITDB_ROOT_PASSWORD: alrussy

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: alrussy
      ME_CONFIG_MONGODB_ADMINPASSWORD: alrussy
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: false
 # in this volume all the data will be saved when you stop/ delete the MongoDB container
