version: '3.8'
name: 'e-ccommerce-API'
services:
  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33066:3306"
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resource:
        limits:
          memory: 500m 