name: product service CI/CD
description: CI/CD pipeline for the inventory service

on:
  push:
    path: inventory_service/**
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./inventory_service
    defaults:
      run:
         working-directory: ${{env.working-directory}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn verify
  

    - if: ${{github.ref =='refs/heads/main'}}
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
 
    - if: ${{github.ref == 'refs/heads/main'}}
      name: Build And Publish Docker Image
      run: |
        mvn  spring-boot:build-image -DskipTests
        docker push ${{secrets.DOCKERHUB_USERNAME}}/e-ccommerce-inventory_service
  
