name: product service CI/CD
description: CI/CD pipeline for the product service

on:
  push:
    path: product_service/**
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./product_service
    defaults:
      run:
         working-directory: ${{env.working-directory}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
  
    - if: ${{github.ref=='refs/heads/main'}}
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
 
    - if: ${{github.ref=='refs/heads/main'}}
      name: Build And Publish Docker Image
      run: 
        mvn  spring-boot:build-image -DskipTests
        docker push ${{securit.DOCKER_NAME}}/e-ccommerce-product_service
